export const paintings = [
  {
    id: 1,
    title: "Distant Horizon",
    year: "2025",
    medium: "Acrylic on canvas",
    dimensions: '36" × 48"',
    image: "/images/painting-distant-horizon.jpg",
    description: "An atmospheric seascape capturing the misty boundary between sea and sky, with soft blues and greens merging into infinite distance.",
    category: "Seascape",
  },
  {
    id: 2,
    title: "Portrait in Light and Shadow",
    year: "2025",
    medium: "Acrylic on canvas",
    dimensions: '24" × 30"',
    image: "/images/painting-portrait-light-shadow.jpg",
    description: "A bold expressionist portrait exploring the duality of human nature through dramatic contrasts of warm and cool tones.",
    category: "Portrait",
  },
  {
    id: 3,
    title: "Mediterranean Coast",
    year: "2025",
    medium: "Acrylic on canvas",
    dimensions: '40" × 50"',
    image: "/images/painting-mediterranean-coast.jpg",
    description: "A vibrant coastal village scene where golden storm clouds give way to clear blue skies, with sailboats dotting the turquoise waters.",
    category: "Coastal",
  },
  {
    id: 4,
    title: "The Outcrop",
    year: "2026",
    medium: "Acrylic on canvas",
    dimensions: "",
    image: "/images/painting-the-outcrop.jpg",
    description: "A solitary dark mass emerges from a luminous teal expanse — rock and sea suspended between sky and water in quiet, brooding tension.",
    category: "Seascape",
  },
  {
    id: 5,
    title: "Turning Tide",
    year: "2026",
    medium: "Acrylic on canvas",
    dimensions: "",
    image: "/images/painting-turning-tide.jpg",
    description: "Stormy greys give way to electric turquoise as the tide turns — white cascades and golden breaks of light cutting through the chaos of the sea.",
    category: "Seascape",
  },
  {
    id: 6,
    title: "The Cottage",
    year: "2026",
    medium: "Acrylic on canvas",
    dimensions: "",
    image: "/images/painting-cottage.jpg",
    description: "A whitewashed cottage nestled beneath a canopy of rich summer trees, dappled light catching the walls and wild red flowers at the garden's edge.",
    category: "Landscape",
  },
  {
    id: 7,
    title: "Green Light",
    year: "2026",
    medium: "Acrylic on canvas",
    dimensions: "",
    image: "/images/painting-green-light.jpg",
    description: "A luminous green glow pierces the dark above a restless sea — foam-flecked waves catching the strange light reflected on still black water below.",
    category: "Seascape",
  },
  {
    id: 8,
    title: "Orange Horizon",
    year: "2026",
    medium: "Acrylic on canvas",
    dimensions: "",
    image: "/images/painting-orange-horizon.jpg",
    description: "A warm amber glow burns low on the horizon, its light spreading across the brooding teal sea in long, trembling reflections.",
    category: "Seascape",
  },
]

export type Painting = typeof paintings[0]
